const initialState = {
  recipes: [
    {
      id: 716426,
      name: "Cauliflower, Brown Rice, and Vegetable Fried Rice",
      img: "https://spoonacular.com/recipeImages/716426-312x231.jpg",
      healthScore: 76,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 715594,
      name: "Homemade Garlic and Basil French Fries",
      img: "https://spoonacular.com/recipeImages/715594-312x231.jpg",
      healthScore: 77,
      diets: ["dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 715497,
      name: "Berry Banana Breakfast Smoothie",
      img: "https://spoonacular.com/recipeImages/715497-312x231.jpg",
      healthScore: 63,
      diets: ["lacto ovo vegetarian"],
    },
    {
      id: 644387,
      name: "Garlicky Kale",
      img: "https://spoonacular.com/recipeImages/644387-312x231.jpg",
      healthScore: 92,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "lacto ovo vegetarian",
        "primal",
        "whole 30",
        "vegan",
      ],
    },
    {
      id: 716268,
      name: "African Chicken Peanut Stew",
      img: "https://spoonacular.com/recipeImages/716268-312x231.jpg",
      healthScore: 100,
      diets: ["gluten free", "dairy free"],
    },
    {
      id: 716381,
      name: "Nigerian Snail Stew",
      img: "https://spoonacular.com/recipeImages/716381-312x231.jpg",
      healthScore: 89,
      diets: ["gluten free", "dairy free", "paleolithic", "primal", "whole 30"],
    },
    {
      id: 782601,
      name: "Red Kidney Bean Jambalaya",
      img: "https://spoonacular.com/recipeImages/782601-312x231.jpg",
      healthScore: 100,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 794349,
      name: "Broccoli and Chickpea Rice Salad",
      img: "https://spoonacular.com/recipeImages/794349-312x231.jpg",
      healthScore: 100,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 715446,
      name: "Slow Cooker Beef Stew",
      img: "https://spoonacular.com/recipeImages/715446-312x231.jpg",
      healthScore: 100,
      diets: ["gluten free", "dairy free"],
    },
    {
      id: 715415,
      name: "Red Lentil Soup with Chicken and Turnips",
      img: "https://spoonacular.com/recipeImages/715415-312x231.jpg",
      healthScore: 73,
      diets: ["gluten free", "dairy free"],
    },
    {
      id: 766453,
      name: "Hummus and Za'atar",
      img: "https://spoonacular.com/recipeImages/766453-312x231.jpg",
      healthScore: 100,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 716627,
      name: "Easy Homemade Rice and Beans",
      img: "https://spoonacular.com/recipeImages/716627-312x231.jpg",
      healthScore: 60,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 716408,
      name: "Greek-Style Baked Fish: Fresh, Simple, and Delicious",
      img: "https://spoonacular.com/recipeImages/716408-312x231.jpg",
      healthScore: 65,
      diets: ["gluten free", "pescatarian"],
    },
    {
      id: 795751,
      name: "Chicken Fajita Stuffed Bell Pepper",
      img: "https://spoonacular.com/recipeImages/795751-312x231.jpg",
      healthScore: 75,
      diets: ["gluten free"],
    },
    {
      id: 640941,
      name: "Crunchy Brussels Sprouts Side Dish",
      img: "https://spoonacular.com/recipeImages/640941-312x231.jpg",
      healthScore: 100,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "lacto ovo vegetarian",
        "primal",
      ],
    },
    {
      id: 798400,
      name: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
      img: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
      healthScore: 87,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 756814,
      name: "Powerhouse Almond Matcha Superfood Smoothie",
      img: "https://spoonacular.com/recipeImages/756814-312x231.jpg",
      healthScore: 54,
      diets: ["gluten free", "dairy free", "whole 30"],
    },
    {
      id: 729366,
      name: "Plantain Salad",
      img: "https://spoonacular.com/recipeImages/729366-312x231.jpg",
      healthScore: 72,
      diets: ["gluten free", "primal", "pescatarian"],
    },
    {
      id: 715769,
      name: "Broccolini Quinoa Pilaf",
      img: "https://spoonacular.com/recipeImages/715769-312x231.jpg",
      healthScore: 74,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 782600,
      name: "Quinoa Salad with Vegetables and Cashews",
      img: "https://spoonacular.com/recipeImages/782600-312x231.jpg",
      healthScore: 66,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 642605,
      name: "Farro With Mushrooms and Asparagus",
      img: "https://spoonacular.com/recipeImages/642605-312x231.jpg",
      healthScore: 80,
      diets: ["dairy free", "lacto ovo vegetarian"],
    },
    {
      id: 715540,
      name: "Summer Berry Salad",
      img: "https://spoonacular.com/recipeImages/715540-312x231.jpg",
      healthScore: 95,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "lacto ovo vegetarian",
        "primal",
        "vegan",
      ],
    },
    {
      id: 636589,
      name: "Butternut Squash Frittata",
      img: "https://spoonacular.com/recipeImages/636589-312x231.jpg",
      healthScore: 100,
      diets: ["gluten free"],
    },
    {
      id: 640062,
      name: "Corn Avocado Salsa",
      img: "https://spoonacular.com/recipeImages/640062-312x231.jpg",
      healthScore: 71,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 715495,
      name: "Turkey Tomato Cheese Pizza",
      img: "https://spoonacular.com/recipeImages/715495-312x231.jpg",
      healthScore: 33,
      diets: [],
    },
    {
      id: 715421,
      name: "Cheesy Chicken Enchilada Quinoa Casserole",
      img: "https://spoonacular.com/recipeImages/715421-312x231.jpg",
      healthScore: 38,
      diets: ["gluten free"],
    },
    {
      id: 716432,
      name: "Finger Foods: Frittata Muffins",
      img: "https://spoonacular.com/recipeImages/716432-312x231.jpg",
      healthScore: 49,
      diets: ["gluten free", "lacto ovo vegetarian", "primal", "ketogenic"],
    },
    {
      id: 716437,
      name: "Chilled Cucumber Avocado Soup with Yogurt and Kefir",
      img: "https://spoonacular.com/recipeImages/716437-312x231.jpg",
      healthScore: 54,
      diets: ["gluten free", "lacto ovo vegetarian", "primal"],
    },
    {
      id: 639535,
      name: "Citrusy Pecan Garbanzo Couscous: A Salad For Cold Weather",
      img: "https://spoonacular.com/recipeImages/639535-312x231.jpg",
      healthScore: 72,
      diets: ["dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 652417,
      name: "Moroccan chickpea and lentil stew",
      img: "https://spoonacular.com/recipeImages/652417-312x231.jpg",
      healthScore: 96,
      diets: ["dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 794538,
      name: "Almond Joy Protein Shake",
      img: "https://spoonacular.com/recipeImages/794538-312x231.jpg",
      healthScore: 78,
      diets: ["gluten free", "dairy free", "fodmap friendly", "ketogenic"],
    },
    {
      id: 648320,
      name: "Jade Buddha Salmon Tartare",
      img: "https://spoonacular.com/recipeImages/648320-312x231.jpg",
      healthScore: 100,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "primal",
        "pescatarian",
      ],
    },
    {
      id: 769774,
      name: "Shredded Roast Beef Stuffed Sweet Potatoes (Whole 30 & PALEO)",
      img: "https://spoonacular.com/recipeImages/769774-312x231.jpg",
      healthScore: 89,
      diets: ["gluten free", "dairy free", "paleolithic", "primal", "whole 30"],
    },
    {
      id: 649931,
      name: "Lentil Salad With Vegetables",
      img: "https://spoonacular.com/recipeImages/649931-312x231.jpg",
      healthScore: 100,
      diets: [
        "gluten free",
        "dairy free",
        "lacto ovo vegetarian",
        "whole 30",
        "vegan",
      ],
    },
    {
      id: 661925,
      name: "Strawberry-Mango Quinoa Salad",
      img: "https://spoonacular.com/recipeImages/661925-312x231.jpg",
      healthScore: 65,
      diets: ["gluten free", "lacto ovo vegetarian"],
    },
    {
      id: 660228,
      name: "Skinny Kale Basil Pesto",
      img: "https://spoonacular.com/recipeImages/660228-312x231.jpg",
      healthScore: 88,
      diets: ["gluten free"],
    },
    {
      id: 715447,
      name: "Easy Vegetable Beef Soup",
      img: "https://spoonacular.com/recipeImages/715447-312x231.jpg",
      healthScore: 65,
      diets: ["dairy free"],
    },
    {
      id: 715543,
      name: "Homemade Guacamole",
      img: "https://spoonacular.com/recipeImages/715543-312x231.jpg",
      healthScore: 34,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "lacto ovo vegetarian",
        "primal",
        "whole 30",
        "vegan",
      ],
    },
    {
      id: 641975,
      name: "Easy Ginger Beef Broccoli",
      img: "https://spoonacular.com/recipeImages/641975-312x231.jpg",
      healthScore: 70,
      diets: ["dairy free"],
    },
    {
      id: 652423,
      name: "Moroccan Couscous and Chickpea Salad",
      img: "https://spoonacular.com/recipeImages/652423-312x231.jpg",
      healthScore: 56,
      diets: ["dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 660306,
      name: "Slow Cooker: Pork and Garbanzo Beans",
      img: "https://spoonacular.com/recipeImages/660306-312x231.jpg",
      healthScore: 75,
      diets: ["gluten free", "dairy free"],
    },
    {
      id: 715424,
      name: "The Best Chili",
      img: "https://spoonacular.com/recipeImages/715424-312x231.jpg",
      healthScore: 34,
      diets: ["gluten free", "dairy free"],
    },
    {
      id: 662670,
      name: "Swiss Chard Wraps",
      img: "https://spoonacular.com/recipeImages/662670-312x231.jpg",
      healthScore: 90,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "lacto ovo vegetarian",
        "primal",
        "vegan",
      ],
    },
    {
      id: 716195,
      name: "Spicy Indian-Style Hummus",
      img: "https://spoonacular.com/recipeImages/716195-312x231.jpg",
      healthScore: 40,
      diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    },
    {
      id: 663559,
      name: "Tomato and lentil soup",
      img: "https://spoonacular.com/recipeImages/663559-312x231.jpg",
      healthScore: 100,
      diets: [
        "gluten free",
        "dairy free",
        "lacto ovo vegetarian",
        "whole 30",
        "vegan",
      ],
    },
    {
      id: 633942,
      name: "Balsamic Roasted Vegetables",
      img: "https://spoonacular.com/recipeImages/633942-312x231.jpg",
      healthScore: 62,
      diets: [
        "gluten free",
        "dairy free",
        "lacto ovo vegetarian",
        "whole 30",
        "vegan",
      ],
    },
    {
      id: 715521,
      name: "Turkey Avocado BLT Salad",
      img: "https://spoonacular.com/recipeImages/715521-312x231.jpg",
      healthScore: 33,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "primal",
        "whole 30",
        "ketogenic",
      ],
    },
    {
      id: 716276,
      name: "Doughnuts",
      img: "https://spoonacular.com/recipeImages/716276-312x231.jpg",
      healthScore: 39,
      diets: ["lacto ovo vegetarian"],
    },
    {
      id: 658509,
      name: "Roasted Broccoli with Lemon and Garlic",
      img: "https://spoonacular.com/recipeImages/658509-312x231.jpg",
      healthScore: 70,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "lacto ovo vegetarian",
        "primal",
        "whole 30",
        "vegan",
      ],
    },
    {
      id: 782622,
      name: "Chocolate Peanut Butter Cinnamon Smoothie",
      img: "https://spoonacular.com/recipeImages/782622-312x231.png",
      healthScore: 100,
      diets: ["gluten free", "dairy free", "fodmap friendly"],
    },
    {
      id: 664547,
      name: "Vegetable Dip",
      img: "https://spoonacular.com/recipeImages/664547-312x231.jpg",
      healthScore: 100,
      diets: ["gluten free", "lacto ovo vegetarian", "primal"],
    },
    {
      id: 661340,
      name: "Spinach Salad with Strawberry Vinaigrette",
      img: "https://spoonacular.com/recipeImages/661340-312x231.jpg",
      healthScore: 78,
      diets: ["gluten free", "primal"],
    },
    {
      id: 715385,
      name: "Slow Cooker Baked Potato Soup",
      img: "https://spoonacular.com/recipeImages/715385-312x231.jpg",
      healthScore: 44,
      diets: [],
    },
    {
      id: 716406,
      name: "Asparagus and Pea Soup: Real Convenience Food",
      img: "https://spoonacular.com/recipeImages/716406-312x231.jpg",
      healthScore: 44,
      diets: [
        "gluten free",
        "dairy free",
        "paleolithic",
        "lacto ovo vegetarian",
        "primal",
        "vegan",
      ],
    },
    {
      id: 658579,
      name: "Roasted Endive Salad With Prosciutto, Figs and Pistachios",
      img: "https://spoonacular.com/recipeImages/658579-312x231.jpg",
      healthScore: 100,
      diets: ["gluten free", "dairy free", "paleolithic", "primal"],
    },
  ],
  // recipes: [{ diets: [] }],
  recipe: { diets: [], instructions: [] },
  diets: [],
};

export default function recipeReducer(state = initialState, action) {
  switch (action.type) {
    case "GET_RECIPES":
      return { ...state, recipes: [...action.payload] };
    case "GET_RECIPE":
      return { ...state, recipe: action.payload };
    case "SEARCH_RECIPES":
      return { ...state, recipes: [...action.payload] };
    case "SET_DIETS":
      return { ...state, diets: [...action.payload] };
    default:
      return state;
  }
}
